"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog"
import { FileText, Loader2, Download, FolderKanban, CheckCircle, Clock, AlertCircle } from "lucide-react"
import { api } from "@/lib/api-client"
import { Card, CardContent } from "@/components/ui/card"
import { format } from "date-fns"

interface CreateReportDialogProps {
    trigger?: React.ReactNode
}

interface ReportData {
    totalProjects: number
    totalTasks: number
    completedTasks: number
    pendingTasks: number
    inProgressTasks: number
    projects: Array<{
        id: string
        name: string
        taskCount: number
        completedTasks: number
    }>
}

export function CreateReportDialog({ trigger }: CreateReportDialogProps) {
    const [open, setOpen] = useState(false)
    const [loading, setLoading] = useState(false)
    const [reportData, setReportData] = useState<ReportData | null>(null)

    useEffect(() => {
        if (open) {
            generateReport()
        }
    }, [open])

    const generateReport = async () => {
        setLoading(true)
        try {
            const { data: projects } = await api.get("/projects")

            let totalTasks = 0
            let completedTasks = 0
            let inProgressTasks = 0

            const projectSummaries = projects.map((p: any) => {
                const taskCount = p.taskCount || 0
                const completed = p.completedTasks || 0
                totalTasks += taskCount
                completedTasks += completed

                return {
                    id: p.id,
                    name: p.name,
                    taskCount,
                    completedTasks: completed
                }
            })

            // Estimate in-progress as 30% of pending (rough estimate)
            const pending = totalTasks - completedTasks
            inProgressTasks = Math.floor(pending * 0.3)

            setReportData({
                totalProjects: projects.length,
                totalTasks,
                completedTasks,
                pendingTasks: pending - inProgressTasks,
                inProgressTasks,
                projects: projectSummaries
            })
        } catch (error) {
            console.error("Failed to generate report", error)
        } finally {
            setLoading(false)
        }
    }

    const downloadReport = () => {
        if (!reportData) return

        const reportText = `
FlowSync Summary Report
Generated: ${format(new Date(), "PPP 'at' p")}
========================================

OVERVIEW
--------
Total Projects: ${reportData.totalProjects}
Total Tasks: ${reportData.totalTasks}
Completed: ${reportData.completedTasks}
In Progress: ${reportData.inProgressTasks}
Pending: ${reportData.pendingTasks}

PROJECT BREAKDOWN
-----------------
${reportData.projects.map(p => `${p.name}: ${p.completedTasks}/${p.taskCount} tasks completed`).join('\n')}

========================================
Report generated by FlowSync
        `.trim()

        const blob = new Blob([reportText], { type: 'text/plain' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `flowsync-report-${format(new Date(), 'yyyy-MM-dd')}.txt`
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        URL.revokeObjectURL(url)
    }

    return (
        <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger asChild>
                {trigger || (
                    <Button variant="outline" className="bg-transparent">
                        <FileText className="mr-2 h-4 w-4" />
                        Create Report
                    </Button>
                )}
            </DialogTrigger>
            <DialogContent className="sm:max-w-[550px]">
                <DialogHeader>
                    <DialogTitle>Summary Report</DialogTitle>
                    <DialogDescription>
                        Overview of your projects and tasks as of {format(new Date(), "PPP")}
                    </DialogDescription>
                </DialogHeader>

                {loading ? (
                    <div className="flex justify-center py-8">
                        <Loader2 className="h-8 w-8 animate-spin text-primary" />
                    </div>
                ) : reportData ? (
                    <div className="space-y-4">
                        {/* Stats Grid */}
                        <div className="grid grid-cols-2 gap-3">
                            <Card>
                                <CardContent className="p-4 flex items-center gap-3">
                                    <FolderKanban className="h-8 w-8 text-primary" />
                                    <div>
                                        <p className="text-2xl font-bold">{reportData.totalProjects}</p>
                                        <p className="text-xs text-muted-foreground">Projects</p>
                                    </div>
                                </CardContent>
                            </Card>
                            <Card>
                                <CardContent className="p-4 flex items-center gap-3">
                                    <CheckCircle className="h-8 w-8 text-success" />
                                    <div>
                                        <p className="text-2xl font-bold">{reportData.completedTasks}</p>
                                        <p className="text-xs text-muted-foreground">Completed</p>
                                    </div>
                                </CardContent>
                            </Card>
                            <Card>
                                <CardContent className="p-4 flex items-center gap-3">
                                    <Clock className="h-8 w-8 text-warning" />
                                    <div>
                                        <p className="text-2xl font-bold">{reportData.inProgressTasks}</p>
                                        <p className="text-xs text-muted-foreground">In Progress</p>
                                    </div>
                                </CardContent>
                            </Card>
                            <Card>
                                <CardContent className="p-4 flex items-center gap-3">
                                    <AlertCircle className="h-8 w-8 text-muted-foreground" />
                                    <div>
                                        <p className="text-2xl font-bold">{reportData.pendingTasks}</p>
                                        <p className="text-xs text-muted-foreground">Pending</p>
                                    </div>
                                </CardContent>
                            </Card>
                        </div>

                        {/* Project List */}
                        {reportData.projects.length > 0 && (
                            <div className="border rounded-lg p-3 max-h-40 overflow-y-auto">
                                <p className="text-sm font-medium mb-2">Project Breakdown</p>
                                <div className="space-y-2">
                                    {reportData.projects.map((project) => (
                                        <div key={project.id} className="flex justify-between text-sm">
                                            <span className="text-muted-foreground">{project.name}</span>
                                            <span className="font-medium">
                                                {project.completedTasks}/{project.taskCount} tasks
                                            </span>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}
                    </div>
                ) : (
                    <p className="text-center text-muted-foreground py-8">
                        No data available
                    </p>
                )}

                <DialogFooter>
                    <Button variant="outline" onClick={() => setOpen(false)}>
                        Close
                    </Button>
                    <Button onClick={downloadReport} disabled={!reportData || loading}>
                        <Download className="mr-2 h-4 w-4" />
                        Download Report
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    )
}
